services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports: 
      - 9090:80
    environment:
      PMA_ARBITRARY: 1 

  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: tasksdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  sistema-notas-back:
    build: 
      context: ./server
    container_name: sistema-notas-back
    ports:
      - 8080:4000
    depends_on: 
      - mysql-db
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 350M
        reservations:
          cpus: '0.2'
          memory: 250M
  
  sistema-notas-front:
    build: 
      context: ./react
    container_name: sistema-notas-front
    ports:
      - 80:80
    depends_on: 
      - sistema-notas-back
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          cpus: '0.15'
          memory: 200M
